[phases.setup]
commands = [
  "npx prisma generate",
  "npx prisma migrate deploy"
]

[phases.install]
commands = [
  "npm install"
]

[phases.build]
commands = [
  "npm run build"
]

[start]
cmd = "node .output/server/index.mjs"
