[phases.setup]
commands = [
  "npx prisma generate"
]

[phases.install]
commands = [
  "npm install"
]

[phases.build]
commands = [
  "npm run build"
]

[start]
cmd = "source .env && node .output/server/index.mjs"
